---
ahoyapi: v2

commands:
  up:
    usage: Build project.
    cmd: docker compose up -d "$@"; ahoy composer install; ahoy sake dev/build

  down:
    usage: Delete project (CAUTION).
    cmd: |
      if [ "$1" == "y" ]; then
        docker compose down
      else
        ahoy confirm "Running this command will destroy your current site, database and build? Are you sure you didn't mean ahoy stop?" &&
        # Run this if confirm returns true
        docker compose down ||
        # Run this if confirm returns false
        echo "OK, probably a wise choice..."
      fi

  open:
    usage: Lauch site in browser
    cmd: open http://nztechweek.docker.amazee.io/

  build:
    usage: Build project.
    cmd: docker compose up -d --build "$@"

  cli:
    usage: Start a shell inside CLI container.
    cmd: docker compose exec cli bash

  run:
    usage: Run command inside CLI container.
    cmd: docker compose exec -T cli bash -c "$@"

  composer:
    usage: Run composer commands in CLI container.
    cmd: docker-compose exec cli composer "$@"

  sake:
    usage: Run sake commands in CLI container.
    cmd: docker compose exec cli sake "$@"

  logs:
    usage: Show Docker logs.
    cmd: docker compose logs "$@"

  ps:
    usage: List running Docker containers.
    cmd: docker-compose ps

  restart:
    usage: Restart Docker containers.
    cmd: docker-compose restart

  stop:
    usage: Stop Docker containers.
    cmd: docker-compose stop "$@"

  confirm:
    cmd: |
      read -r -p "$@ [y/N] " response
      if [[ $response = y ]]
      then
        true
      else
        false
      fi
    hide: true
